//
// File generated by rootcint at Thu Jun 15 15:29:29 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME TerminatordODict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "Terminator.Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void Terminator_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_Terminator(void *p = 0);
   static void *newArray_Terminator(Long_t size, void *p);
   static void delete_Terminator(void *p);
   static void deleteArray_Terminator(void *p);
   static void destruct_Terminator(void *p);
   static void streamer_Terminator(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::Terminator*)
   {
      ::Terminator *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::Terminator >(0);
      static ::ROOT::TGenericClassInfo 
         instance("Terminator", ::Terminator::Class_Version(), "./Terminator.hh", 7,
                  typeid(::Terminator), ::ROOT::DefineBehavior(ptr, ptr),
                  &::Terminator::Dictionary, isa_proxy, 0,
                  sizeof(::Terminator) );
      instance.SetNew(&new_Terminator);
      instance.SetNewArray(&newArray_Terminator);
      instance.SetDelete(&delete_Terminator);
      instance.SetDeleteArray(&deleteArray_Terminator);
      instance.SetDestructor(&destruct_Terminator);
      instance.SetStreamerFunc(&streamer_Terminator);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::Terminator*)
   {
      return GenerateInitInstanceLocal((::Terminator*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Terminator*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr Terminator::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *Terminator::Class_Name()
{
   return "Terminator";
}

//______________________________________________________________________________
const char *Terminator::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::Terminator*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int Terminator::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::Terminator*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void Terminator::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::Terminator*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *Terminator::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::Terminator*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void Terminator::Streamer(TBuffer &R__b)
{
   // Stream an object of class Terminator.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> count;
      R__b.CheckByteCount(R__s, R__c, Terminator::IsA());
   } else {
      R__c = R__b.WriteVersion(Terminator::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << count;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void Terminator::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class Terminator.
      TClass *R__cl = ::Terminator::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "count", &count);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_Terminator(void *p) {
      return  p ? new(p) ::Terminator : new ::Terminator;
   }
   static void *newArray_Terminator(Long_t nElements, void *p) {
      return p ? new(p) ::Terminator[nElements] : new ::Terminator[nElements];
   }
   // Wrapper around operator delete
   static void delete_Terminator(void *p) {
      delete ((::Terminator*)p);
   }
   static void deleteArray_Terminator(void *p) {
      delete [] ((::Terminator*)p);
   }
   static void destruct_Terminator(void *p) {
      typedef ::Terminator current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_Terminator(TBuffer &buf, void *obj) {
      ((::Terminator*)obj)->::Terminator::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::Terminator

/********************************************************
* Terminator.Dict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTerminatordODict();

extern "C" void G__set_cpp_environmentTerminatordODict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("Terminator.hh");
  G__cpp_reset_tagtableTerminatordODict();
}
#include <new>
extern "C" int G__cpp_dllrevTerminatordODict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Terminator */
static int G__TerminatordODict_224_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Terminator* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Terminator[n];
     } else {
       p = new((void*) gvp) Terminator[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Terminator;
     } else {
       p = new((void*) gvp) Terminator;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TerminatordODictLN_Terminator));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TerminatordODict_224_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Terminator*) G__getstructoffset())->Terminate();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TerminatordODict_224_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) Terminator::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TerminatordODict_224_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Terminator::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TerminatordODict_224_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) Terminator::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TerminatordODict_224_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      Terminator::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TerminatordODict_224_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Terminator*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TerminatordODict_224_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Terminator::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TerminatordODict_224_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Terminator::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TerminatordODict_224_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Terminator::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TerminatordODict_224_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Terminator::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TerminatordODict_224_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   Terminator* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new Terminator(*(Terminator*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TerminatordODictLN_Terminator));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Terminator G__TTerminator;
static int G__TerminatordODict_224_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Terminator*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Terminator*) (soff+(sizeof(Terminator)*i)))->~G__TTerminator();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Terminator*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Terminator*) (soff))->~G__TTerminator();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TerminatordODict_224_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Terminator* dest = (Terminator*) G__getstructoffset();
   *dest = *(Terminator*) libp->para[0].ref;
   const Terminator& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Terminator */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTerminatordODict {
 public:
  G__Sizep2memfuncTerminatordODict(): p(&G__Sizep2memfuncTerminatordODict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTerminatordODict::*p)();
};

size_t G__get_sizep2memfuncTerminatordODict()
{
  G__Sizep2memfuncTerminatordODict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTerminatordODict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TerminatordODictLN_Terminator))) {
     Terminator *G__Lderived;
     G__Lderived=(Terminator*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TerminatordODictLN_Terminator),G__get_linked_tagnum(&G__TerminatordODictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTerminatordODict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TerminatordODictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TerminatordODictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TerminatordODictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TerminatordODictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TerminatordODictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TerminatordODictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TerminatordODictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TerminatordODictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TerminatordODictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TerminatordODictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TerminatordODictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TerminatordODictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__TerminatordODictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__TerminatordODictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__TerminatordODictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Terminator */
static void G__setup_memvarTerminator(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TerminatordODictLN_Terminator));
   { Terminator *p; p=(Terminator*)0x1000; if (p) { }
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"count=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TerminatordODictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTerminatordODict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTerminator(void) {
   /* Terminator */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TerminatordODictLN_Terminator));
   G__memfunc_setup("Terminator",1061,G__TerminatordODict_224_0_1, 105, G__get_linked_tagnum(&G__TerminatordODictLN_Terminator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Terminate",937,G__TerminatordODict_224_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TerminatordODict_224_0_3, 85, G__get_linked_tagnum(&G__TerminatordODictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&Terminator::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TerminatordODict_224_0_4, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Terminator::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TerminatordODict_224_0_5, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&Terminator::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TerminatordODict_224_0_6, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&Terminator::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TerminatordODictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TerminatordODict_224_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TerminatordODict_224_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Terminator::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TerminatordODict_224_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Terminator::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TerminatordODict_224_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Terminator::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TerminatordODict_224_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Terminator::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("Terminator", 1061, G__TerminatordODict_224_0_15, (int) ('i'), G__get_linked_tagnum(&G__TerminatordODictLN_Terminator), -1, 0, 1, 1, 1, 0, "u 'Terminator' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~Terminator", 1187, G__TerminatordODict_224_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TerminatordODict_224_0_17, (int) ('u'), G__get_linked_tagnum(&G__TerminatordODictLN_Terminator), -1, 1, 1, 1, 1, 0, "u 'Terminator' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTerminatordODict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTerminatordODict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTerminatordODict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TerminatordODictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TerminatordODictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TerminatordODictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TerminatordODictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TerminatordODictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TerminatordODictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TerminatordODictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TerminatordODictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TerminatordODictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__TerminatordODictLN_Terminator = { "Terminator" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTerminatordODict() {
  G__TerminatordODictLN_TClass.tagnum = -1 ;
  G__TerminatordODictLN_TBuffer.tagnum = -1 ;
  G__TerminatordODictLN_TMemberInspector.tagnum = -1 ;
  G__TerminatordODictLN_TObject.tagnum = -1 ;
  G__TerminatordODictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TerminatordODictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TerminatordODictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TerminatordODictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TerminatordODictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__TerminatordODictLN_Terminator.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTerminatordODict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TerminatordODictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TerminatordODictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TerminatordODictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TerminatordODictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TerminatordODictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TerminatordODictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TerminatordODictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TerminatordODictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TerminatordODictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TerminatordODictLN_Terminator),sizeof(Terminator),-1,29952,(char*)NULL,G__setup_memvarTerminator,G__setup_memfuncTerminator);
}
extern "C" void G__cpp_setupTerminatordODict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTerminatordODict()");
  G__set_cpp_environmentTerminatordODict();
  G__cpp_setup_tagtableTerminatordODict();

  G__cpp_setup_inheritanceTerminatordODict();

  G__cpp_setup_typetableTerminatordODict();

  G__cpp_setup_memvarTerminatordODict();

  G__cpp_setup_memfuncTerminatordODict();
  G__cpp_setup_globalTerminatordODict();
  G__cpp_setup_funcTerminatordODict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTerminatordODict();
  return;
}
class G__cpp_setup_initTerminatordODict {
  public:
    G__cpp_setup_initTerminatordODict() { G__add_setup_func("TerminatordODict",(G__incsetup)(&G__cpp_setupTerminatordODict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTerminatordODict() { G__remove_setup_func("TerminatordODict"); }
};
G__cpp_setup_initTerminatordODict G__cpp_setup_initializerTerminatordODict;

