/********************************************************************
* Terminator.Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Terminator.Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTerminatordODict();
extern void G__cpp_setup_inheritanceTerminatordODict();
extern void G__cpp_setup_typetableTerminatordODict();
extern void G__cpp_setup_memvarTerminatordODict();
extern void G__cpp_setup_globalTerminatordODict();
extern void G__cpp_setup_memfuncTerminatordODict();
extern void G__cpp_setup_funcTerminatordODict();
extern void G__set_cpp_environmentTerminatordODict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Terminator.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TerminatordODictLN_TClass;
extern G__linked_taginfo G__TerminatordODictLN_TBuffer;
extern G__linked_taginfo G__TerminatordODictLN_TMemberInspector;
extern G__linked_taginfo G__TerminatordODictLN_TObject;
extern G__linked_taginfo G__TerminatordODictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TerminatordODictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TerminatordODictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TerminatordODictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TerminatordODictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TerminatordODictLN_Terminator;

/* STUB derived class for protected member access */
